---
title: "Exploded code"
subtitle: "Using flipbookr and xaringan"
author: "Me"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r, include = T}
# This is the recommended set up for flipbooks
# you might think about setting cache to TRUE as you gain practice --- building flipbooks from scratch can be time consuming
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, message = F, warning = FALSE, comment = "", cache = F)

options(tibble.print_min = 55)
options(knitr.duplicate.label = "allow")
options(width=300) # prevents data wrapping
```


```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 70%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```



```{r}
library(tidyverse)
read.csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-21/spotify_songs.csv") ->
  songs

#' Title
#'
#' @param data 
#' @param z 
#' @param z_q_range 
#' @param z_value 
#' @param tolerance 
#' @param tol_value 
#'
#' @return
#' @export
#'
#' @examples
ggslice <- function(data, z, 
                    z_q_range = .5, # middle of the range
                    z_value = NULL, 
                    tolerance = .05, # plus or minus 5% of range
                    tol_value = NULL){
  
z_vector <- data |> pull({{z}})  
z_range <- range(z_vector, na.rm = T)
z_name <- data  |>  select({{z}}) |> names()
  
if(is.null(z_value)){z_value <- z_range |> quantile(z_q_range)}
if(is.null(tol_value)){tol_value <- (z_range[2]-z_range[1])*tolerance}

z_min <- z_value - tol_value
z_max <- z_value + tol_value
  
data %>% 
  dplyr::filter({{z}} <= z_max & {{z}} >= z_min) |> 
  dplyr::mutate(closeness = (tol_value - abs(z_value - {{z}}))/tol_value)  ->
sliced
  
sliced |>
  ggplot2::ggplot() + 
  ggplot2::geom_blank(data = data) + 
  ggplot2::labs(subtitle = paste0(z_name, " slice = ", 
                                  round(z_value, 2),"\u00B1",  
                                  round(tol_value,2))) +
  # scale_color_viridis_c(limits = range(z_complete, na.rm = T)) + 
  theme(panel.background = element_rect(fill = alpha("midnightblue", z_q_range))) +
    theme(panel.grid = element_line(color = alpha("white", 1-z_q_range))) +

  NULL
  
}
```

---

`r flipbookr::chunk_reveal("songs", break_type = "replace", replace = "0.6", replacements = seq(0.000, 1, by = .01))`


```{r songs, include = F}
library(ggslice)

songs %>% 
  mutate(ind_tswift = track_artist |> str_detect("Taylor Swift")) %>% 
  arrange(ind_tswift) %>% 
  ggslice(z = valence, z_q_range = 0.6) + 
  aes(danceability, energy) + 
  geom_point(aes(alpha = closeness, color = ind_tswift)) +
  scale_alpha(limits = c(0, 1)) + 
  geom_smooth(method = lm) +
  scale_fill_viridis_c(limits = range(songs$valence)) + 
  scale_color_manual(values = c("white", "darkred")) +
  geom_text(hjust = -.07, 
            aes(label = str_extract(track_name, ".{2,12}") %>% paste("..."), 
                alpha = closeness), 
            data = . %>% filter(ind_tswift))
```

